source 'https://rubygems.org'
gem "activerecord"
gem "mysql2", '~> 0.4.0'
gem 'composite_primary_keys', '>8.0.0'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'rake'
gem 'archive-tar-minitar', '~> 0.5.2'
gem 'ferver'
gem 'pry'
gem 'pry-nav'
gem 'activesupport', '~> 4.2', '>= 4.2.5'
gem 'rest-client'
gem 'elasticsearch'